# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      input-num-1: 
        description: "First input"
        required: true

      input-num-2: 
          description: "Second input"
          required: true

env:
  file: python.py
  file1: document.py

  input-num-1: ${{github.event.inputs.input-num-1}}
  input-num-2: ${{github.event.inputs.input-num-2}}


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job
  job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: python $file $input-num-1

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: echo $msg

  job2:
    # needs: job1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
      
      - name: Run a second-line script
        run: |
          python $file1 $input-num-2
